Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2:
> > 
> > > Patch Set 2: Code-Review-1
> > > 
> > > why are you copying this code from their respective repos?
> > 
> > Hi, the helm charts for license management works well when we deploy them independently. But when we try to deploy them into same namespace, there is a conflict about the acumos-registry
> > secret. Since the Acumos docker repo doesn't need the pull image secret, I took that part out. Also I have a concern about the init db script in lum-helm, the reference will not work if we push the chats to a helm repo.
> > 
> > But we are not sure that code change will affect the current Acumos deployment. So we decided to save the charts in system-integration repo. Once we test the charts we would contribute that back to license management project.
> 
> It is difficult to determine what you copied and what you changed do you have a list of files you changed to fix the items above? Ok to be clear this is just a test case and not planned to merge into master. Keeping -1 we should use subcharts or use helmfile to pull in multiple helm charts. We do not want to maintain multiple copies of helm + sql files. I have tested the charts with different namespaces or the same as acumos and didn't face issues other than the docker registry secret which had to be created only if using a different namespace other than acumos. I was using helm 3 without tiller for my testing. What version of helm are you using/testing with? Is there any documentation of running helm install you are trying to get working?

Here is the test result for, I was using helm 3 to deploy both rtu-editor and profile-editor into a new namespace. Got "existing resource conflict". So I applied a simple temporary fix for that.

1. removed / templates / docker-secret.yaml from both chart.
2. modify the deployment.yaml took out the  imagePullSecrets part

As mentioned this is just a temporary fix, if we want to pull images from private docker repo other that acumos nexus3, the docker-secret is needed. But the component helm chart should not create that secret object. A helm chart for acumos prerequisite should create all the shared objects for all the acumos components. 
 
****@Azure:~/license-manager$ helm install rtu --namespace license-test license-rtu-editor-helm-chart/
NAME: rtu
LAST DEPLOYED: Mon Mar  2 15:32:56 2020
NAMESPACE: license-test
STATUS: deployed
REVISION: 1
NOTES:
1. Get the application URL by running these commands:
  export POD_NAME=$(kubectl get pods --namespace license-test -l "app.kubernetes.io/name=license-rtu-editor-helm-chart,app.kubernetes.io/instance=rtu" -o jsonpath="{.items[0].metadata.name}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl port-forward $POD_NAME 8080:80
****@Azure:~/license-manager$ helm install profile --namespace license-test license-profile-editor-helm-chart/
Error: rendered manifests contain a resource that already exists. Unable to continue with install: existing resource conflict: namespace: license-test, name: acumos-registry, existing_kind: /v1, Kind=Secret, new_kind: /v1, Kind=Secret

Patch-set: 2