Update patch set 13
Patch Set 13:

One more alarming message but I think it causes no trouble:

    Removing network acumos_default
    ERROR: network acumos_default has active endpoints

Patch-set: 13